### PR TITLE
guix.scm: Fix guilesitedir for recipe.

### PR DESCRIPTION
**Pull request by a-sassmannshausen**
* guix.scm: Change source to point to local tarball.  This works for the
  workflow proposed in the file.  override guilesitedir with a guix specific
  path.

### CODE REVIEW

**Comment by a-sassmannshausen** [comment]
Hi Artyom,

Thank you for merging the previous pull requests.  As it happened I had figured out how to make the version agnostic configure.ac work for Guix — so here you'll find an update to the repository's guix package recipe implementing that.

It also switches the source specification to point to a local tarball.  This works because the source spec is not used for the `guix environment -l guix.scm`, after which a tarball can be generated using make dist.

The benefit is that it removes a requirement to link to a specific commit in the guix package recipe.

Hope this makes sense!

Alex

PS: I will be submitting a package to guix today, with the previous issues resolved.

**Comment by artyom-poptsov** [comment]
Hello Alex,

unfortunately I'm not very familiar with GNU Guix ways of working with packages yet.  Currently I'm trying to make myself a working Guix environment in a Docker container.

> It also switches the source specification to point to a local tarball. This works because the source spec is not used for the guix environment -l guix.scm, after which a tarball can be generated using make dist.

Well, it means that users will have to get the package not by Guix itself, but by some other means, right? I think it'll simplify the package recipe indeed and will make the process of preparing new Guile-DSV release easier for such a not-yet-Guix-user as myself, but getting the package through Guix seems to be more convenient for Guix users.

Anyways, I'm going to make a new release with this pull request merged.

Thanks,

Artyom

**Comment by a-sassmannshausen** [comment]
Hi Artyom,

Artyom V. Poptsov writes:

> Hello Alex,
>
> unfortunately I'm not very familiar with GNU Guix ways of working with
> packages yet. Currently I'm trying to make myself a working Guix
> environment in a Docker container.

Exciting! Always nice to see a new user :-)

>
>  It also switches the source specification to point to a local
>  tarball. This works because the source spec is not used for the guix
>  environment -l guix.scm, after which a tarball can be generated using
>  make dist.
>
> Well, it means that users will have to get the package not by Guix
> itself, but by some other means, right? I think it'll simplify the
> package recipe indeed and will make the process of preparing new
> Guile-DSV release easier for such a not-yet-Guix-user as myself, but
> getting the package through Guix seems to be more convenient for Guix
> users.

Actually, Guix users just wanting to install the package will just use
the guix package that comes with the distribution.  The Guix file that
is part of this repo is just a super convenient way to hack on
guile-dsv.

You will probably see what I mean by that when you have a docker
environment: you can just do guix environment -l guix.scm and you'll end
up with all the dependencies for guile-dsv installed.

> Anyways, I'm going to make a new release with this pull request
> merged.

Good to hear :-)

Alex

**Comment by artyom-poptsov** [comment]
Hello Alex,

I released Guile-DSV: https://lists.gnu.org/archive/html/guile-user/2017-11/msg00054.html

`guix.scm` updated as well.  Could you please update the GNU Guix package?

Besides, I'm available on #guix and #guile IRC channels (my "nickname" is `artyom-poptsov`, duh) -- feel free to contact me there if you have any questions related to my projects (or any Guile-related questions for that matter.)

Thanks,

Artyom

**Comment by a-sassmannshausen** [comment]
Hiya,

Artyom V. Poptsov writes:

> Hello Alex,
>
> I released Guile-DSV: https://lists.gnu.org/archive/html/guile-user/2017-11/msg00054.html
>
> guix.scm updated as well. Could you please update the GNU Guix package?
>
> Besides, I'm available on #guix and #guile IRC channels (my "nickname" is artyom-poptsov, duh) -- feel free to contact me there if you have any questions related to my projects (or any Guile-related questions for that matter.)

Congrats on the new release! :-)

I've now bumped the version of the package in Guix.  Thanks for your
contact details.  I'm not often on IRC, but when I am, I am atheia.

Alex

**Pull request merged**
